// Generated by CoffeeScript 1.6.2
(function() {
  var fs;

  fs = require('fs');

  task('build', "Build all source files", function() {
    var coffee;

    coffee = require('coffee-script').compile;
    fs.readFile('./src/jpelcompress.coffee', 'utf8', function(err, data) {
      var coffeeData, exec;

      if (err) {
        throw err;
      }
      coffeeData = coffee(data);
      fs.writeFile('./js/jpelcompress.js', coffeeData);
      fs.writeFileSync('./bin/jpelcompress', '#!/usr/bin/env node\n' + coffeeData);
      exec = require('child_process').exec;
      return exec('chmod +x ./bin/jpelcompress');
    });
    return fs.readFile('./src/JPEllucent.coffee', 'utf8', function(err, data) {
      if (err) {
        throw err;
      }
      return fs.writeFile('./js/JPEllucent.js', coffee(data));
    });
  });

}).call(this);
